### PR TITLE
Added support to TEMPer1V1.1 (TEMPer1F1.1Per1F)

### PR DESCRIPTION
**Pull request by e-minguez**
Before:
```
$ ./temper.py -l
...
Bus 004 Dev 002 0c45:7401 * TEMPer1V1.1 ['hidraw0', 'hidraw1']

$ ./temper.py --json
[
    {
        "vendorid": 3141,
        "productid": 29697,
        "manufacturer": "RDing",
        "product": "TEMPer1V1.1",
        "busnum": 4,
        "devnum": 2,
        "devices": [
            "hidraw0",
            "hidraw1"
        ],
        "firmware": "TEMPer1F1.1Per1F",
        "hex_firmware": "54454d5065723146312e315065723146",
        "hex_data": "8002135065723146",
        "error": "Unknown firmware TEMPer1F1.1Per1F: b'8002135065723146'"
    }
]

$ ./temper.py --json --verbose
Firmware query: b'0186ff0100000000'
Firmware value: b'54454d5065723146312e315065723146' TEMPer1F1.1Per1F
Data value: b'8002135065723146'
[
    {
        "vendorid": 3141,
        "productid": 29697,
        "manufacturer": "RDing",
        "product": "TEMPer1V1.1",
        "busnum": 4,
        "devnum": 2,
        "devices": [
            "hidraw0",
            "hidraw1"
        ],
        "firmware": "TEMPer1F1.1Per1F",
        "hex_firmware": "54454d5065723146312e315065723146",
        "hex_data": "8002135065723146",
        "error": "Unknown firmware TEMPer1F1.1Per1F: b'8002135065723146'"
    }
]
```

After the change:

```
$ ./temper.py 
Bus 004 Dev 002 0c45:7401 TEMPer1F1. 19.31C 66.76F - - - -

$ ./temper.py --json
[
    {
        "vendorid": 3141,
        "productid": 29697,
        "manufacturer": "RDing",
        "product": "TEMPer1V1.1",
        "busnum": 4,
        "devnum": 2,
        "devices": [
            "hidraw0",
            "hidraw1"
        ],
        "firmware": "TEMPer1F1.",
        "hex_firmware": "54454d5065723146312e315065723146",
        "hex_data": "8002135065723146",
        "internal temperature": 19.3125
    }
]

$ ./temper.py --json --verbose
Firmware query: b'0186ff0100000000'
Firmware value: b'54454d5065723146312e315065723146' TEMPer1F1.1Per1F
Data value: b'8002135065723146'
[
    {
        "vendorid": 3141,
        "productid": 29697,
        "manufacturer": "RDing",
        "product": "TEMPer1V1.1",
        "busnum": 4,
        "devnum": 2,
        "devices": [
            "hidraw0",
            "hidraw1"
        ],
        "firmware": "TEMPer1F1.",
        "hex_firmware": "54454d5065723146312e315065723146",
        "hex_data": "8002135065723146",
        "internal temperature": 19.3125
    }
]
```

### CODE REVIEW

**Comment by eode** [comment]
If you also update the table in `README.md` and do a PR on [ccwienk/temper](https://github.com/ccwienk/temper), we'll push this out to PyPI (temper-py).

**Comment by e-minguez** [comment]
> If you also update the table in `README.md` and do a PR on [ccwienk/temper](https://github.com/ccwienk/temper), we'll push this out to PyPI (temper-py).

Updated the table here and created PR on that repo as well https://github.com/ccwienk/temper/pull/2

**Comment by eode** [comment]
Thanks, released.

Say, is that detected as in internal sensor, same as with the `temper1F`?

**Comment by e-minguez** [comment]
> Thanks, released.
> 
> Say, is that detected as in internal sensor, same as with the `temper1F`?

No idea, the output is attached in the first comment, but I don't know how to check if it is detected as an internal sensor or not.

**Comment by eode** [comment]
that answered my question, thanks.

**Comment by urwen** [comment]
This was merged via https://github.com/ccwienk/temper
Thank you for your contribution!

**Pull request closed without merging**
